const DATA_API_URL='https://ep-muddy-fire-awvetyx3.apirest.c-12.us-east-1.aws.neon.tech/americaestuya/rest/v1';
let reportSession={token:'',accountId:null};
let reportRows=[];
let reportColumns=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
window.addEventListener('management:session',e=>{reportSession={token:e.detail.token,accountId:e.detail.accountId}});
async function ensureSession(){if(reportSession.token)return reportSession;const [{getApps,getApp},{getAuth}]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js')]);for(let i=0;i<80&&!getApps().length;i++)await new Promise(r=>setTimeout(r,100));const auth=getAuth(getApp());if(typeof auth.authStateReady==='function')await auth.authStateReady();if(!auth.currentUser)throw new Error('No hay una sesión activa');reportSession.token=await auth.currentUser.getIdToken();return reportSession}
function addReportMenu(){const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-section="report"]')){const a=document.createElement('a');a.href='#report';a.dataset.section='report';a.innerHTML='<span class="icon">📊</span><span>Generar Reporte</span>';a.addEventListener('click',e=>{e.preventDefault();window.managementShowSection?.('report')});nav.appendChild(a)}const picker=document.getElementById('sectionSelect');if(picker&&!picker.querySelector('option[value="report"]')){const o=document.createElement('option');o.value='report';o.textContent='Generar Reporte';picker.appendChild(o)}}
function addReportSection(){if(document.getElementById('report'))return;const main=document.querySelector('main.content');const section=document.createElement('section');section.id='report';section.className='card section';section.innerHTML=`<style>.report-editor{width:100%;min-height:155px;border:1px solid #cbdbe7;border-radius:12px;padding:12px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:14px;line-height:1.45;color:#173f61;background:#fff;resize:vertical}.report-grid-wrap{margin-top:16px;overflow:auto;border:1px solid #dce7f0;border-radius:14px;max-height:58vh}.report-grid{border-collapse:collapse;width:max-content;min-width:100%;background:#fff}.report-grid th,.report-grid td{border-bottom:1px solid #e5edf3;border-right:1px solid #eef3f7;padding:9px 11px;text-align:left;white-space:nowrap}.report-grid th{position:sticky;top:0;background:#eef5fb;color:#214c6c;font-weight:900;z-index:1}.report-grid td{color:#355b76}.report-empty{padding:25px;text-align:center;color:#6b8295}.report-export-wrap{position:relative}.report-export-menu{display:none;position:absolute;top:44px;right:0;z-index:40;min-width:145px;background:#fff;border:1px solid #d7e4ed;border-radius:12px;box-shadow:0 12px 30px #153f6130;padding:6px}.report-export-menu.open{display:grid}.report-export-menu button{border:0;background:#fff;text-align:left;padding:10px;border-radius:8px;color:#244d6c;font-weight:700}.report-export-menu button:hover{background:#eef6fb}</style><div class="toolstrip" id="reportToolbar"><button class="tool-btn" type="button" id="reportRun" title="Ejecutar query" aria-label="Ejecutar query"><svg viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg></button><span class="tool-sep"></span><span class="report-export-wrap"><button class="tool-btn" type="button" id="reportExport" title="Exportar" aria-label="Exportar"><svg viewBox="0 0 24 24"><path d="M12 3v12M8 11l4 4 4-4M5 21h14"/></svg></button><span class="report-export-menu" id="reportExportMenu"><button data-format="csv">CSV</button><button data-format="pdf">PDF</button><button data-format="excel">EXCEL</button><button data-format="jpg">JPG</button></span></span></div><textarea id="reportSql" class="report-editor" spellcheck="false" placeholder="SELECT ...\nFROM ...\nWHERE ...\nORDER BY ..."></textarea><div id="reportStatus" class="status"></div><div id="reportGridWrap" class="report-grid-wrap"><div class="report-empty">Escribe un SELECT y pulsa Query.</div></div>`;main.appendChild(section)}
function splitAnd(where){return where.split(/\s+and\s+/i).map(x=>x.trim()).filter(Boolean)}
function unquote(v){v=v.trim();if(/^'.*'$/.test(v)||/^".*"$/.test(v))return v.slice(1,-1);return v}
function parseSql(sql){sql=sql.trim().replace(/;\s*$/,'');if(!/^select\s/i.test(sql))throw new Error('Solo SELECT está permitido.');if(/;/.test(sql))throw new Error('Usa una sola consulta SELECT.');const low=sql.toLowerCase();const fromPos=low.indexOf(' from ');if(fromPos<0)throw new Error('Falta FROM.');let selectPart=sql.slice(6,fromPos).trim();let rest=sql.slice(fromPos+6).trim();const kw=(text,key)=>{const m=new RegExp('\\s+'+key+'\\s+','i').exec(text);return m?m.index:-1};const positions=[['where',kw(rest,'where')],['order by',kw(rest,'order\\s+by')],['limit',kw(rest,'limit')]].filter(x=>x[1]>=0).sort((a,b)=>a[1]-b[1]);const first=positions[0]?.[1]??rest.length;const table=rest.slice(0,first).trim();if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(table))throw new Error('Por ahora FROM admite una sola tabla.');const pieces={};for(let i=0;i<positions.length;i++){const [name,pos]=positions[i];const start=pos+name.replace('order by','order by').length+2;const end=positions[i+1]?.[1]??rest.length;pieces[name]=rest.slice(start,end).trim()}const cols=selectPart==='*'?'*':selectPart.split(',').map(x=>x.trim()).join(',');let params=new URLSearchParams();params.set('select',cols||'*');if(pieces.where){for(const c of splitAnd(pieces.where)){const m=c.match(/^([A-Za-z_][\w]*)\s*(=|!=|<>|>=|<=|>|<|ilike|like)\s*(.+)$/i);if(!m)throw new Error('WHERE no reconocido: '+c);const [,col,op0,raw]=m;const op=op0.toLowerCase();let val=unquote(raw);let pgop={'=':'eq','!=':'neq','<>':'neq','>':'gt','<':'lt','>=':'gte','<=':'lte','like':'like','ilike':'ilike'}[op];if(/^null$/i.test(val)){pgop='is';val='null'}params.append(col,`${pgop}.${val}`)}}if(pieces['order by']){const order=pieces['order by'].split(',').map(x=>{const m=x.trim().match(/^([A-Za-z_][\w]*)(?:\s+(asc|desc))?$/i);if(!m)throw new Error('ORDER BY no reconocido: '+x);return `${m[1]}.${(m[2]||'asc').toLowerCase()}`}).join(',');params.set('order',order)}const lim=pieces.limit?Math.min(Math.max(parseInt(pieces.limit,10)||500,1),1000):500;params.set('limit',String(lim));return {table,params}}
function setStatus(text,type=''){const s=document.getElementById('reportStatus');s.textContent=text||'';s.className='status'+(type?' '+type:'')}
function renderGrid(rows){reportRows=Array.isArray(rows)?rows:[];reportColumns=reportRows.length?[...new Set(reportRows.flatMap(r=>Object.keys(r)))]:[];const wrap=document.getElementById('reportGridWrap');if(!reportRows.length){wrap.innerHTML='<div class="report-empty">La consulta no devolvió filas.</div>';return}wrap.innerHTML=`<table class="report-grid"><thead><tr>${reportColumns.map(c=>`<th>${esc(c)}</th>`).join('')}</tr></thead><tbody>${reportRows.map(r=>`<tr>${reportColumns.map(c=>`<td>${esc(r[c]==null?'':typeof r[c]==='object'?JSON.stringify(r[c]):r[c])}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
async function runReport(){try{setStatus('');const sql=document.getElementById('reportSql').value;const {table,params}=parseSql(sql);await ensureSession();const r=await fetch(`${DATA_API_URL}/${table}?${params}`,{headers:{Authorization:`Bearer ${reportSession.token}`,'X-America-Raw-State':'1'}});if(!r.ok)throw new Error(await r.text());const rows=await r.json();renderGrid(rows);setStatus(`${rows.length} fila(s).`,'success')}catch(e){console.error(e);setStatus('ERROR REAL: '+(e?.message||e),'error')}}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportCsv(){const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=[reportColumns.map(q).join(','),...reportRows.map(r=>reportColumns.map(c=>q(r[c])).join(','))].join('\n');download(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),'reporte.csv')}
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function exportExcel(){if(!reportRows.length)return;if(!window.XLSX)await loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js');const ws=XLSX.utils.json_to_sheet(reportRows,{header:reportColumns});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Reporte');XLSX.writeFile(wb,'reporte.xlsx')}
async function exportPdf(){if(!reportRows.length)return;if(!window.jspdf)await loadScript('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js');if(!window.jspdf.jsPDF.API.autoTable)await loadScript('https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.4/dist/jspdf.plugin.autotable.min.js');const {jsPDF}=window.jspdf;const doc=new jsPDF({orientation:'landscape'});doc.autoTable({head:[reportColumns],body:reportRows.map(r=>reportColumns.map(c=>String(r[c]??''))),styles:{fontSize:7}});doc.save('reporte.pdf')}
function exportJpg(){if(!reportRows.length)return;const cw=180,rowH=28,w=Math.max(720,reportColumns.length*cw),h=Math.min(12000,(reportRows.length+1)*rowH+20),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,w,h);x.font='bold 14px Arial';x.fillStyle='#173f61';reportColumns.forEach((col,i)=>x.fillText(String(col).slice(0,22),i*cw+8,20));x.font='13px Arial';reportRows.slice(0,Math.floor((h-rowH)/rowH)).forEach((r,ri)=>{x.fillStyle='#355b76';reportColumns.forEach((col,i)=>x.fillText(String(r[col]??'').slice(0,24),i*cw+8,(ri+2)*rowH-8))});c.toBlob(b=>download(b,'reporte.jpg'),'image/jpeg',0.92)}
function exportFormat(f){if(!reportRows.length){setStatus('Primero ejecuta una consulta.','error');return}if(f==='csv')exportCsv();else if(f==='excel')exportExcel().catch(e=>setStatus(e.message,'error'));else if(f==='pdf')exportPdf().catch(e=>setStatus(e.message,'error'));else if(f==='jpg')exportJpg()}
function wire(){addReportMenu();addReportSection();const picker=document.getElementById('sectionSelect');picker?.addEventListener('change',()=>{if(picker.value==='report')window.managementShowSection?.('report')},true);document.getElementById('reportRun').onclick=runReport;document.getElementById('reportExport').onclick=e=>{e.stopPropagation();document.getElementById('reportExportMenu').classList.toggle('open')};document.getElementById('reportExportMenu').addEventListener('click',e=>{const b=e.target.closest('[data-format]');if(!b)return;exportFormat(b.dataset.format);document.getElementById('reportExportMenu').classList.remove('open')});document.addEventListener('click',e=>{if(!e.target.closest('.report-export-wrap'))document.getElementById('reportExportMenu')?.classList.remove('open')})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();