const DATA_API_URL='https://ep-muddy-fire-awvetyx3.apirest.c-12.us-east-1.aws.neon.tech/americaestuya/rest/v1';
const section=document.getElementById('configuration');
if(!section) throw new Error('No se encontró Configuración');

const FILE_DEFAULTS=['.doc','.docx','.pdf','.jpg','.jpeg','.png'];
const el=id=>document.getElementById(id);
let token='',rows=[],rootsById=new Map(),selectedParentId=null,selectedValueId=null,parentSortAsc=true,valueSortAsc=true,activeView='parents';

const style=document.createElement('style');
style.textContent=`
.section:not(.active){display:none!important}.cfg-view{display:none!important}.cfg-view.active{display:block!important}
.cfg-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;border:1px solid #e0eaf1;border-radius:14px;padding:14px 15px;background:#fff;cursor:pointer}
.cfg-row:hover{border-color:#b9d4e8;background:#fbfdff}.cfg-row.selected{border-color:#1785d1;box-shadow:0 0 0 2px #1785d119;background:#f3f9fd}
.cfg-name{font-weight:900;font-size:17px;color:#153f61}.cfg-meta{margin-top:5px;color:#6b8295;font-size:13px;display:flex;gap:10px;flex-wrap:wrap}
.cfg-side{display:flex;align-items:center;gap:8px}.cfg-apply{font-size:12px;font-weight:900;border-radius:999px;padding:6px 9px;background:#edf5fb;color:#315b7a;white-space:nowrap}
.cfg-values-btn{width:40px;height:40px;border:1px solid #d5e3ed;border-radius:10px;background:#f7fbfe;color:#24638f;display:grid;place-items:center;cursor:pointer}.cfg-values-btn:hover{background:#e8f4fc}
.cfg-values-btn svg{width:21px;height:21px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}
.cfg-back-detail{border:0;background:#eef5fb;color:#07589b;border-radius:10px;width:40px;height:40px;font-size:22px;cursor:pointer}.cfg-headline{display:flex;align-items:center;gap:10px}.cfg-headline h1{margin:0}
.cfg-searchbar{display:none;gap:8px;margin-bottom:14px}.cfg-searchbar.open{display:flex}.cfg-searchbar input,.cfg-searchbar select{height:42px;border:1px solid #cbdbe7;border-radius:10px;padding:0 11px;background:#fff;color:#173f61}.cfg-searchbar input{flex:1;min-width:0}
.cfg-delete-dialog{border:0;border-radius:18px;padding:0;box-shadow:0 24px 70px #102f4960;max-width:420px;width:calc(100% - 34px)}.cfg-delete-dialog::backdrop{background:#102f4966}.cfg-delete-box{padding:22px}.cfg-delete-actions{display:flex;gap:9px;flex-wrap:wrap}.cfg-delete-actions button{border-radius:10px;padding:10px 14px;font-weight:800;cursor:pointer}
.cfg-export-wrap{position:relative}.cfg-export-menu{position:absolute;right:0;top:46px;z-index:50;min-width:145px;padding:6px;background:#fff;border:1px solid #d7e4ed;border-radius:12px;box-shadow:0 12px 28px #153f6130;display:none}.cfg-export-menu.open{display:grid}.cfg-export-menu button{border:0;background:#fff;text-align:left;padding:10px 12px;border-radius:8px;color:#244d6c;font-weight:700;cursor:pointer}.cfg-export-menu button:hover{background:#eef6fb}
.tool-btn[disabled]{opacity:.28;pointer-events:none}.cfg-tool-save.active-form,.cfg-tool-cancel.active-form{background:#e7f3fc;color:#07589b}
@media(max-width:760px){.cfg-section-title{display:none}.cfg-row{grid-template-columns:1fr auto}.cfg-searchbar{flex-direction:column}.cfg-searchbar input,.cfg-searchbar select{width:100%}.cfg-side{gap:5px}}
`;
document.head.appendChild(style);

const icons={new:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',edit:'<svg viewBox="0 0 24 24"><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg>',save:'<svg viewBox="0 0 24 24"><path d="M5 3h12l2 2v16H5z"/><path d="M8 3v6h8V3M8 21v-8h8v8"/></svg>',cancel:'<svg viewBox="0 0 24 24"><path d="M6 6l12 12M18 6L6 18"/></svg>',delete:'<svg viewBox="0 0 24 24"><path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6M10 11v5M14 11v5"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',filter:'<svg viewBox="0 0 24 24"><path d="M4 5h16l-6 7v6l-4 2v-8Z"/></svg>',sort:'<svg viewBox="0 0 24 24"><path d="M8 6v12M5 9l3-3 3 3M16 18V6M13 15l3 3 3-3"/></svg>',print:'<svg viewBox="0 0 24 24"><path d="M6 9V3h12v6M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2M6 14h12v7H6z"/></svg>',export:'<svg viewBox="0 0 24 24"><path d="M12 3v12M8 11l4 4 4-4M5 21h14"/></svg>',values:'<svg viewBox="0 0 24 24"><path d="M8 6h13M8 12h13M8 18h13"/><circle cx="3" cy="6" r="1"/><circle cx="3" cy="12" r="1"/><circle cx="3" cy="18" r="1"/></svg>'};
const tool=(action,label,extra='')=>`<button class="tool-btn ${extra}" type="button" data-action="${action}" title="${label}" aria-label="${label}">${icons[action]}</button>`;
const toolbar=()=>tool('new','Nuevo')+tool('edit','Modificar')+tool('save','Guardar','cfg-tool-save')+tool('cancel','Cancelar','cfg-tool-cancel')+tool('delete','Eliminar')+'<span class="tool-sep"></span>'+tool('search','Buscar')+tool('filter','Filtrar')+tool('sort','Ordenar por ORDEN ascendente/descendente')+'<span class="tool-sep"></span>'+tool('print','Imprimir')+`<span class="cfg-export-wrap">${tool('export','Descargar')}<span class="cfg-export-menu"><button type="button" data-export="csv">CSV</button><button type="button" data-export="pdf">PDF</button><button type="button" data-export="excel">EXCEL</button><button type="button" data-export="jpg">JPG</button></span></span>`;

section.innerHTML=`
<div id="cfgParentView" class="cfg-view active">
  <div class="section-head cfg-section-title"><h1>Configuración</h1></div>
  <div class="toolstrip" id="cfgParentTools">${toolbar()}</div><div id="cfgParentStatus" class="status"></div>
  <div id="cfgParentSearch" class="cfg-searchbar"><input id="cfgParentSearchText" type="search" placeholder="Buscar"><select id="cfgApplyFilter"><option value="ALL_ITEMS">Todos</option><option value="ALL">Aplica a todos</option><option value="ACCOUNT">Cuenta</option><option value="CLIENT">Cliente</option><option value="USER">Usuario</option></select></div>
  <form id="cfgParentForm" class="client-form"><input id="cfgParentId" type="hidden"><div class="form-grid"><div class="field full"><label for="cfgParentName">Nombre</label><input id="cfgParentName" maxlength="80" required></div><div class="field"><label for="cfgParentType">Tipo de dato</label><select id="cfgParentType"><option value="TEXT">Texto</option><option value="MEMO">Memo</option><option value="NUMBER">Número</option><option value="DATETIME">Fecha Hora</option><option value="BOOLEAN">Booleano</option><option value="LIST">Lista de valores</option><option value="FILE">Archivo</option></select></div><div class="field"><label for="cfgParentApply">A quién aplica</label><select id="cfgParentApply"><option value="ALL">Todos</option><option value="ACCOUNT">Cuenta</option><option value="CLIENT">Cliente</option><option value="USER">Usuario</option></select></div><div class="field full"><label for="cfgParentDescription">Descripción</label><input id="cfgParentDescription" maxlength="180"></div><div class="field"><label for="cfgParentOrder">Orden</label><input id="cfgParentOrder" type="number" min="0" step="1" value="10"></div></div><button type="submit" hidden>Guardar</button></form>
  <div id="cfgParentsList" class="clients-list"><div class="no-items">Cargando…</div></div>
</div>
<div id="cfgValuesView" class="cfg-view">
  <div class="section-head cfg-headline"><button id="cfgBackValues" class="cfg-back-detail" type="button" aria-label="Volver">←</button><div><h1 id="cfgValuesHeading">Detalles</h1></div></div>
  <div class="toolstrip" id="cfgValueTools">${toolbar()}</div><div id="cfgValueStatus" class="status"></div>
  <div id="cfgValueSearch" class="cfg-searchbar"><input id="cfgValueSearchText" type="search" placeholder="Buscar detalle"><select id="cfgValueFilter"><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></div>
  <form id="cfgValueForm" class="client-form"><input id="cfgValueId" type="hidden"><div class="form-grid"><div class="field full"><label for="cfgValueName">Nombre</label><input id="cfgValueName" maxlength="80" required></div><div id="cfgSecondField" class="field full"><label id="cfgValueSecondLabel" for="cfgValueSecond">Descripción</label><input id="cfgValueSecond" maxlength="180"></div><div class="field"><label for="cfgValueOrder">Orden</label><input id="cfgValueOrder" type="number" min="0" step="1" value="10"></div></div><button type="submit" hidden>Guardar</button></form>
  <div id="cfgValuesList" class="clients-list"><div class="no-items">Selecciona una configuración.</div></div>
</div>
<dialog id="cfgDeleteDialog" class="cfg-delete-dialog"><form method="dialog" class="cfg-delete-box"><div style="font-size:21px;font-weight:900;margin-bottom:8px">Eliminar registro</div><div style="margin-bottom:18px">¿Qué deseas hacer con <strong id="cfgDeleteName"></strong>?</div><div class="cfg-delete-actions"><button value="inactivate">Inactivar</button><button value="delete">Borrar</button><button value="cancel">Cancelar</button></div></form></dialog>`;

const typeLabel={TEXT:'Texto',MEMO:'Memo',NUMBER:'Número',DATETIME:'Fecha Hora',BOOLEAN:'Booleano',LIST:'Lista de valores',FILE:'Archivo',LONG_TEXT:'Memo',EMAIL:'Texto',INTEGER:'Número',DECIMAL:'Número',DATE_DMY:'Fecha Hora',DATE_MDY:'Fecha Hora',TIME_12:'Fecha Hora',TIME_24:'Fecha Hora'};
const applyLabel={ALL:'Todos',ACCOUNT:'Cuenta',CLIENT:'Cliente',USER:'Usuario'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const normalizeType=t=>({LONG_TEXT:'MEMO',EMAIL:'TEXT',INTEGER:'NUMBER',DECIMAL:'NUMBER',DATE_DMY:'DATETIME',DATE_MDY:'DATETIME',TIME_12:'DATETIME',TIME_24:'DATETIME'}[t]||t||'TEXT');
const isLV=t=>['LIST','FILE'].includes(normalizeType(t));
const defaultFormat=t=>({TEXT:'TEXT',MEMO:'MEMO',NUMBER:'###',DATETIME:'DD/MM/YYYY',BOOLEAN:'YES/NO',LIST:'LIST',FILE:'LIST'}[normalizeType(t)]||'TEXT');
function setMsg(box,text,type=''){box.textContent=text||'';box.className='status'+(type?' '+type:'')}
function selectedParent(){return rows.find(r=>String(r.id_sequence)===String(selectedParentId))||null}
function selectedValue(){return rows.find(r=>String(r.id_sequence)===String(selectedValueId))||null}
function byOrder(a,b,asc){const ao=Number(a.display_order??0),bo=Number(b.display_order??0);if(ao!==bo)return asc?ao-bo:bo-ao;const n=String(a.name||'').localeCompare(String(b.name||''),'es',{sensitivity:'base'});return asc?n:-n}
function parentRows(){const candidates=rows.filter(r=>rootsById.has(String(r.id_parent))&&r.deleted_at==null&&r.is_active!==false);const seen=new Map();for(const r of candidates){const key=String(r.name||'').trim().toLowerCase();const prev=seen.get(key);if(!prev||Number(r.id_sequence)<Number(prev.id_sequence))seen.set(key,r)}let out=[...seen.values()];const q=el('cfgParentSearchText').value.trim().toLowerCase(),f=el('cfgApplyFilter').value;if(q)out=out.filter(r=>[r.name,r.description,typeLabel[r.data_type],applyLabel[r.applies_to||'ALL']].some(v=>String(v||'').toLowerCase().includes(q)));if(f!=='ALL_ITEMS')out=out.filter(r=>(r.applies_to||'ALL')===f);return out.sort((a,b)=>byOrder(a,b,parentSortAsc))}
function valueRows(){const p=selectedParent();if(!p)return[];let out=rows.filter(r=>String(r.id_parent)===String(p.id_sequence)&&r.deleted_at==null);const q=el('cfgValueSearchText').value.trim().toLowerCase(),f=el('cfgValueFilter').value;if(q)out=out.filter(r=>[r.name,r.description,r.format].some(v=>String(v||'').toLowerCase().includes(q)));if(f==='active')out=out.filter(r=>r.is_active!==false);if(f==='inactive')out=out.filter(r=>r.is_active===false);return out.sort((a,b)=>byOrder(a,b,valueSortAsc))}
function secondLabelFor(p){return isLV(p?.data_type)?'Descripción':'Formato'}
function secondValueFor(v,p){return isLV(p?.data_type)?(v?.description||''):(v?.format||'')}
function refreshTools(which){const form=which==='values'?el('cfgValueForm'):el('cfgParentForm'),box=which==='values'?el('cfgValueTools'):el('cfgParentTools');if(!form||!box)return;const open=form.classList.contains('open');box.querySelectorAll('[data-action="save"],[data-action="cancel"]').forEach(b=>{b.disabled=!open;b.classList.toggle('active-form',open)})}
function closeAllExportMenus(){document.querySelectorAll('.cfg-export-menu.open').forEach(m=>m.classList.remove('open'))}
function renderParents(){const ps=parentRows();if(!ps.some(r=>String(r.id_sequence)===String(selectedParentId)))selectedParentId=null;el('cfgParentsList').innerHTML=ps.length?ps.map(p=>`<div class="cfg-row ${String(p.id_sequence)===String(selectedParentId)?'selected':''}" data-id="${p.id_sequence}"><div><div class="cfg-name">${esc(p.name)}</div><div class="cfg-meta"><span>Orden ${p.display_order??'—'}</span><span>${esc(typeLabel[p.data_type]||typeLabel[normalizeType(p.data_type)]||p.data_type)}</span><span>${esc(p.format||'')}</span></div></div><div class="cfg-side"><span class="cfg-apply">${esc(applyLabel[p.applies_to||'ALL']||'Todos')}</span><button class="cfg-values-btn" type="button" data-values="${p.id_sequence}" title="Detalles">${icons.values}</button></div></div>`).join(''):'<div class="no-items">Sin datos configurados</div>';el('cfgParentsList').querySelectorAll('.cfg-row').forEach(r=>r.addEventListener('click',()=>{selectedParentId=r.dataset.id;renderParents()}));el('cfgParentsList').querySelectorAll('[data-values]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();selectedParentId=b.dataset.values;selectedValueId=null;showValues(true)}))}
function renderValues(){const p=selectedParent(),vs=valueRows();el('cfgValuesHeading').textContent=p?`Detalles · ${p.name}`:'Detalles';if(!vs.some(r=>String(r.id_sequence)===String(selectedValueId)))selectedValueId=null;el('cfgValuesList').innerHTML=p?(vs.length?vs.map(v=>`<div class="cfg-row ${String(v.id_sequence)===String(selectedValueId)?'selected':''}" data-id="${v.id_sequence}"><div><div class="cfg-name">${esc(v.name)}</div><div class="cfg-meta">${normalizeType(p.data_type)==='FILE'?'':`<span>${esc(secondLabelFor(p))}: ${esc(secondValueFor(v,p)||'—')}</span>`}<span>Orden ${v.display_order??'—'}</span></div></div><span class="cfg-apply">${v.is_active===false?'Inactivo':'Activo'}</span></div>`).join(''):'<div class="no-items">Todavía no tiene detalles</div>'):'<div class="no-items">Selecciona una configuración</div>';el('cfgValuesList').querySelectorAll('.cfg-row').forEach(r=>r.addEventListener('click',()=>{selectedValueId=r.dataset.id;renderValues()}))}
function showParents(){activeView='parents';closeValueForm();el('cfgValuesView').classList.remove('active');el('cfgParentView').classList.add('active');renderParents();refreshTools('parents')}
function showValues(push){const p=selectedParent();if(!p)return;activeView='values';closeParentForm();el('cfgParentView').classList.remove('active');el('cfgValuesView').classList.add('active');closeValueForm();renderValues();refreshTools('values');if(push){history.replaceState({...history.state,cfgParents:true},'',location.href);history.pushState({cfgValues:true,parentId:String(p.id_sequence)},'',`#configuration-details-${p.id_sequence}`)}}
function openParentForm(row=null){closeValueForm();el('cfgParentId').value=row?.id_sequence||'';el('cfgParentName').value=row?.name||'';el('cfgParentType').value=normalizeType(row?.data_type||'TEXT');el('cfgParentApply').value=row?.applies_to||'ALL';el('cfgParentDescription').value=row?.description||'';el('cfgParentOrder').value=row?.display_order??10;el('cfgParentForm').classList.add('open');refreshTools('parents')}
function closeParentForm(){if(!el('cfgParentForm'))return;el('cfgParentForm').classList.remove('open');el('cfgParentForm').reset();el('cfgParentId').value='';refreshTools('parents')}
function openValueForm(row=null){const p=selectedParent();if(!p)return;closeParentForm();const isFile=normalizeType(p.data_type)==='FILE';el('cfgValueId').value=row?.id_sequence||'';el('cfgValueName').value=row?.name||'';el('cfgSecondField').style.display=isFile?'none':'';el('cfgValueSecondLabel').textContent=secondLabelFor(p);el('cfgValueSecond').value=row?secondValueFor(row,p):'';el('cfgValueOrder').value=row?.display_order??10;el('cfgValueForm').classList.add('open');refreshTools('values')}
function closeValueForm(){if(!el('cfgValueForm'))return;el('cfgValueForm').classList.remove('open');el('cfgValueForm').reset();el('cfgValueId').value='';el('cfgSecondField').style.display='';refreshTools('values')}
function chooseDeleteAction(name){const dlg=el('cfgDeleteDialog');el('cfgDeleteName').textContent=name||'este registro';return new Promise(resolve=>{const done=()=>{dlg.removeEventListener('close',done);resolve(dlg.returnValue||'cancel')};dlg.addEventListener('close',done);dlg.showModal()})}
async function api(path,options={}){const r=await fetch(DATA_API_URL+path,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw new Error(await r.text());if(r.status===204)return null;const text=await r.text();return text?JSON.parse(text):null}
async function ensureCatalogRoot(){let root=rows.find(r=>r.id_parent==null&&r.name==='ADDITIONAL_FIELDS'&&r.deleted_at==null);if(root)return root;const saved=await api('/igldata',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id_parent:null,name:'ADDITIONAL_FIELDS',description:'Catálogo único de datos adicionales',data_type:'LIST',format:'LIST',display_order:5,is_active:true,applies_to:'ALL'})});root=Array.isArray(saved)?saved[0]:null;if(!root)throw new Error('No se pudo crear el catálogo');return root}
async function load(){const data=await api('/igldata?select=id_sequence,id_parent,name,description,data_type,format,display_order,is_active,deleted_at,applies_to&deleted_at=is.null&order=display_order.asc,id_sequence.asc');rows=Array.isArray(data)?data:[];rootsById=new Map(rows.filter(r=>r.id_parent==null).map(r=>[String(r.id_sequence),r]));renderParents();renderValues()}
async function ensureFileDefaults(parentId,appliesTo='ALL'){const existing=new Set(rows.filter(r=>String(r.id_parent)===String(parentId)&&r.deleted_at==null).map(r=>String(r.name||'').trim().toLowerCase()));const missing=FILE_DEFAULTS.filter(ext=>!existing.has(ext));if(!missing.length)return;await api('/igldata',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(missing.map((ext,i)=>({id_parent:Number(parentId),name:ext,description:ext,data_type:'TEXT',format:'TEXT',display_order:(i+1)*10,is_active:true,applies_to:appliesTo})))})}
async function saveParent(){const id=el('cfgParentId').value,name=el('cfgParentName').value.trim(),type=el('cfgParentType').value;if(!name)return false;let parentId=id?rows.find(r=>String(r.id_sequence)===String(id))?.id_parent:(await ensureCatalogRoot()).id_sequence;const payload={id_parent:Number(parentId),name,description:el('cfgParentDescription').value.trim()||name,data_type:type,format:defaultFormat(type),display_order:Number(el('cfgParentOrder').value||0),is_active:true,applies_to:el('cfgParentApply').value};let saved;if(id)saved=await api(`/igldata?id_sequence=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...payload,updated_at:new Date().toISOString()})});else saved=await api('/igldata',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});const row=Array.isArray(saved)?saved[0]:null,savedId=row?.id_sequence||id;if(savedId)selectedParentId=savedId;await load();if(type==='FILE'&&savedId){await ensureFileDefaults(savedId,payload.applies_to);await load()}closeParentForm();return true}
async function saveValue(){const p=selectedParent();if(!p)return false;const id=el('cfgValueId').value,name=el('cfgValueName').value.trim(),second=el('cfgValueSecond').value.trim();if(!name)return false;const listLike=isLV(p.data_type),isFile=normalizeType(p.data_type)==='FILE';const payload={id_parent:Number(p.id_sequence),name,description:isFile?name:(listLike?(second||name):name),data_type:'TEXT',format:listLike?'TEXT':(second||defaultFormat(p.data_type)),display_order:Number(el('cfgValueOrder').value||0),is_active:true,applies_to:p.applies_to||'ALL'};if(id)await api(`/igldata?id_sequence=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...payload,updated_at:new Date().toISOString()})});else await api('/igldata',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});closeValueForm();selectedValueId=null;await load();renderValues();return true}
async function removeParent(){const p=selectedParent();if(!p)return;const action=await chooseDeleteAction(p.name);if(action==='cancel')return;if(action==='inactivate')await api(`/igldata?id_sequence=eq.${p.id_sequence}`,{method:'PATCH',body:JSON.stringify({is_active:false,updated_at:new Date().toISOString()})});else await api(`/igldata?id_sequence=eq.${p.id_sequence}`,{method:'DELETE'});selectedParentId=null;await load()}
async function removeValue(){const v=selectedValue();if(!v)return;const action=await chooseDeleteAction(v.name);if(action==='cancel')return;if(action==='inactivate')await api(`/igldata?id_sequence=eq.${v.id_sequence}`,{method:'PATCH',body:JSON.stringify({is_active:false,updated_at:new Date().toISOString()})});else await api(`/igldata?id_sequence=eq.${v.id_sequence}`,{method:'DELETE'});selectedValueId=null;await load();renderValues()}
function exportData(isValues){const data=isValues?valueRows():parentRows(),p=selectedParent();if(isValues)return{header:['Nombre','Orden','Estado'],rows:data.map(r=>[r.name,r.display_order,r.is_active===false?'Inactivo':'Activo']),name:'detalles'};return{header:['Nombre','Tipo','Aplica a','Formato','Descripción','Orden'],rows:data.map(r=>[r.name,typeLabel[r.data_type]||r.data_type,applyLabel[r.applies_to||'ALL']||'Todos',r.format,r.description,r.display_order]),name:'configuracion'}}
function downloadBlob(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function exportCsv(isValues){const d=exportData(isValues),q=v=>'"'+String(v??'').replaceAll('"','""')+'"',csv='\ufeff'+[d.header,...d.rows].map(r=>r.map(q).join(',')).join('\r\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),d.name+'.csv')}
function exportExcel(isValues){const d=exportData(isValues),xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Datos"><Table>${[d.header,...d.rows].map((r,ri)=>`<Row>${r.map(v=>`<Cell><Data ss:Type="String">${esc(v)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`;downloadBlob(new Blob([xml],{type:'application/vnd.ms-excel'}),d.name+'.xls')}
function tableCanvas(isValues){const d=exportData(isValues),rs=[d.header,...d.rows].map(r=>r.map(v=>String(v??''))),font='16px Arial',pad=12,rowH=36,measure=document.createElement('canvas').getContext('2d');measure.font=font;const widths=d.header.map((_,i)=>Math.min(330,Math.max(110,...rs.map(r=>measure.measureText(r[i]||'').width+pad*2)))),canvas=document.createElement('canvas');canvas.width=Math.min(2400,widths.reduce((a,b)=>a+b,0));canvas.height=Math.min(12000,rowH*rs.length+2);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.textBaseline='middle';ctx.strokeStyle='#cfdde8';ctx.fillStyle='#173f61';let y=1;rs.forEach((r,ri)=>{let x=0;r.forEach((v,i)=>{const w=widths[i];ctx.strokeRect(x,y,w,rowH);ctx.font=ri===0?'bold 16px Arial':font;ctx.fillText(v.slice(0,50),x+pad,y+rowH/2);x+=w});y+=rowH});return{canvas,name:d.name}}
function exportJpg(isValues){const t=tableCanvas(isValues);t.canvas.toBlob(b=>{if(b)downloadBlob(b,t.name+'.jpg')},'image/jpeg',0.92)}
function escapePdfText(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?').replace(/([\\()])/g,'\\$1')}
function exportPdf(isValues){const d=exportData(isValues),lines=[d.header.join(' | '),...d.rows.map(r=>r.join(' | '))].map(s=>escapePdfText(s).slice(0,105)),pageLines=46,pages=[];for(let i=0;i<lines.length;i+=pageLines)pages.push(lines.slice(i,i+pageLines));const objs=['<< /Type /Catalog /Pages 2 0 R >>'];const pageIds=[];for(let i=0;i<pages.length;i++)pageIds.push(4+i*2);objs.push(`<< /Type /Pages /Kids [${pageIds.map(id=>id+' 0 R').join(' ')}] /Count ${pages.length} >>`);objs.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');pages.forEach((page,pi)=>{const pageId=4+pi*2,contentId=pageId+1;objs.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`);const text=['BT','/F1 9 Tf','36 756 Td',...page.flatMap((line,i)=>i===0?[`(${line}) Tj`]:['0 -15 Td',`(${line}) Tj`]),'ET'].join('\n');objs.push(`<< /Length ${text.length} >>\nstream\n${text}\nendstream`)});let pdf='%PDF-1.4\n',offsets=[0];objs.forEach((o,i)=>{offsets[i+1]=pdf.length;pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objs.length;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;downloadBlob(new Blob([pdf],{type:'application/pdf'}),d.name+'.pdf')}
function doExport(f,isValues){if(f==='csv')exportCsv(isValues);else if(f==='excel')exportExcel(isValues);else if(f==='jpg')exportJpg(isValues);else if(f==='pdf')exportPdf(isValues)}
async function saveFromToolbar(isValues,status){try{const form=isValues?el('cfgValueForm'):el('cfgParentForm');if(!form.classList.contains('open'))return;const ok=isValues?await saveValue():await saveParent();if(ok){setMsg(status,'Guardado.','success');setTimeout(()=>setMsg(status,''),1200)}}catch(err){console.error(err);setMsg(status,'ERROR REAL: '+(err?.message||String(err)),'error')}}
function handleTools(which,e){const exportChoice=e.target.closest('[data-export]');if(exportChoice){doExport(exportChoice.dataset.export,which==='values');closeAllExportMenus();return}const b=e.target.closest('.tool-btn');if(!b||b.disabled)return;const a=b.dataset.action,isValues=which==='values',status=isValues?el('cfgValueStatus'):el('cfgParentStatus');setMsg(status,'');if(a==='print')return window.print();if(a==='export'){b.closest('.cfg-export-wrap').querySelector('.cfg-export-menu').classList.toggle('open');return}if(a==='save')return saveFromToolbar(isValues,status);if(a==='cancel')return isValues?closeValueForm():closeParentForm();if(a==='search'){(isValues?el('cfgValueSearch'):el('cfgParentSearch')).classList.toggle('open');return}if(a==='filter'){(isValues?el('cfgValueSearch'):el('cfgParentSearch')).classList.add('open');return}if(a==='sort'){if(isValues){valueSortAsc=!valueSortAsc;renderValues()}else{parentSortAsc=!parentSortAsc;renderParents()}return}if(a==='new')return isValues?openValueForm():openParentForm();if(a==='edit'){if(isValues){const v=selectedValue();if(v)openValueForm(v)}else{const p=selectedParent();if(p)openParentForm(p)}return}if(a==='delete')return(isValues?removeValue():removeParent()).catch(err=>setMsg(status,'ERROR REAL: '+err.message,'error'))}

el('cfgParentTools').addEventListener('click',e=>handleTools('parents',e));el('cfgValueTools').addEventListener('click',e=>handleTools('values',e));el('cfgParentSearchText').addEventListener('input',renderParents);el('cfgApplyFilter').addEventListener('change',renderParents);el('cfgValueSearchText').addEventListener('input',renderValues);el('cfgValueFilter').addEventListener('change',renderValues);el('cfgParentForm').addEventListener('submit',e=>{e.preventDefault();saveFromToolbar(false,el('cfgParentStatus'))});el('cfgValueForm').addEventListener('submit',e=>{e.preventDefault();saveFromToolbar(true,el('cfgValueStatus'))});el('cfgBackValues').onclick=()=>history.state?.cfgValues?history.back():showParents();window.addEventListener('popstate',e=>{const st=e.state||{};if(st.cfgValues&&st.parentId){selectedParentId=st.parentId;showValues(false)}else if(activeView==='values'||st.cfgParents)showParents()});document.addEventListener('click',e=>{if(!e.target.closest('.cfg-export-wrap'))closeAllExportMenus()});refreshTools('parents');refreshTools('values');

(async()=>{try{const [{getApps,getApp},{getAuth}]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js')]);for(let i=0;i<80&&!getApps().length;i++)await new Promise(r=>setTimeout(r,100));if(!getApps().length)throw new Error('Firebase no está inicializado');const auth=getAuth(getApp());if(typeof auth.authStateReady==='function')await auth.authStateReady();if(!auth.currentUser)throw new Error('No hay una sesión activa');token=await auth.currentUser.getIdToken();await load()}catch(e){console.error(e);setMsg(el('cfgParentStatus'),'No se pudo iniciar Configuración: '+(e?.message||e),'error')}})();