const FIREBASE_CONFIG={apiKey:'AIzaSyCanpMR3uSiZAecwLYG9nWiXvaksJncX0U',authDomain:'americaestuya.firebaseapp.com',projectId:'americaestuya',storageBucket:'americaestuya.firebasestorage.app',messagingSenderId:'1071710933035',appId:'1:1071710933035:web:2443a0ec9f1405fcc61a6e',measurementId:'G-8K579LVLX1'};
const DATA_API_URL='https://ep-muddy-fire-awvetyx3.apirest.c-12.us-east-1.aws.neon.tech/americaestuya/rest/v1';
const section=document.getElementById('configuration');
if(!section) throw new Error('No se encontró la sección Configuración');

const style=document.createElement('style');
style.textContent=`
.config-wrap{display:grid;gap:16px}.config-top{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.config-top .field{min-width:220px;flex:1}.config-grid{display:grid;grid-template-columns:minmax(280px,.85fr) minmax(320px,1.15fr);gap:16px}.config-panel{border:1px solid #dce7f0;border-radius:15px;overflow:hidden;background:#fff}.config-panel-head{display:flex;align-items:center;gap:8px;padding:12px 14px;background:#f7fafc;border-bottom:1px solid #e2ebf2}.config-panel-head b{font-size:16px}.config-actions{margin-left:auto;display:flex;gap:6px}.config-mini{border:1px solid #ccdce8;background:#fff;color:#24506f;border-radius:9px;padding:7px 10px;font-weight:800;cursor:pointer}.config-mini.primary{background:#0b78c5;color:#fff;border-color:#0b78c5}.config-list{display:grid;gap:7px;padding:10px;max-height:520px;overflow:auto}.config-row{border:1px solid #e2ebf2;border-radius:11px;padding:11px 12px;background:#fff;cursor:pointer}.config-row:hover{background:#f8fbfd}.config-row.selected{border-color:#1785d1;background:#f0f8fe;box-shadow:0 0 0 2px #1785d115}.config-row-title{font-weight:900;color:#163f61}.config-row-meta{font-size:12px;color:#6e8598;margin-top:4px}.config-empty{padding:22px;color:#718698;text-align:center}.config-status{display:none;padding:10px 12px;border-radius:10px}.config-status.error{display:block;background:#fff1f1;color:#982f2f}.config-status.success{display:block;background:#edf9f1;color:#26784b}.config-modal{position:fixed;inset:0;background:#082d4d70;display:none;place-items:center;padding:18px;z-index:1000}.config-modal.open{display:grid}.config-dialog{width:min(520px,100%);background:#fff;border-radius:18px;padding:20px;box-shadow:0 24px 70px #001f3f55}.config-dialog h2{margin:0 0 16px}.config-dialog .form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.config-dialog .field.full{grid-column:1/-1}.config-dialog input,.config-dialog select{width:100%;height:43px;border:1px solid #cbdbe7;border-radius:10px;padding:0 11px;background:#fff}.config-dialog .buttons{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}@media(max-width:760px){.config-grid{grid-template-columns:1fr}.config-panel{min-width:0}.config-dialog .form-grid{grid-template-columns:1fr}.config-dialog .field.full{grid-column:auto}}
`;
document.head.appendChild(style);

section.innerHTML=`
<div class="section-head"><h1>Configuración</h1></div>
<div id="cfgStatus" class="config-status"></div>
<div class="config-wrap">
  <div class="config-top">
    <div class="field"><label for="cfgGroup">Datos adicionales de</label><select id="cfgGroup"><option value="ACCOUNT_FIELDS">Cuenta</option><option value="CLIENT_FIELDS">Clientes</option><option value="USER_FIELDS">Usuarios</option></select></div>
  </div>
  <div class="config-grid">
    <div class="config-panel">
      <div class="config-panel-head"><b>Campos</b><div class="config-actions"><button id="cfgNewField" class="config-mini primary" type="button">+ Nuevo</button><button id="cfgEditField" class="config-mini" type="button">Modificar</button></div></div>
      <div id="cfgFields" class="config-list"><div class="config-empty">Cargando…</div></div>
    </div>
    <div class="config-panel">
      <div class="config-panel-head"><b id="cfgValuesTitle">Valores hijos</b><div class="config-actions"><button id="cfgNewValue" class="config-mini primary" type="button">+ Valor</button><button id="cfgEditValue" class="config-mini" type="button">Modificar</button></div></div>
      <div id="cfgValues" class="config-list"><div class="config-empty">Selecciona un campo de tipo lista.</div></div>
    </div>
  </div>
</div>
<div id="cfgModal" class="config-modal" aria-hidden="true"><form id="cfgForm" class="config-dialog"><h2 id="cfgFormTitle">Nuevo campo</h2><input id="cfgId" type="hidden"><input id="cfgParent" type="hidden"><input id="cfgMode" type="hidden"><div class="form-grid"><div class="field full"><label for="cfgName">Nombre</label><input id="cfgName" maxlength="80" required></div><div class="field full"><label for="cfgDescription">Descripción</label><input id="cfgDescription" maxlength="180"></div><div class="field"><label for="cfgType">Tipo</label><select id="cfgType"><option value="TEXT">Texto</option><option value="LONG_TEXT">Texto largo</option><option value="EMAIL">Correo</option><option value="INTEGER">Entero</option><option value="DECIMAL">Decimal</option><option value="DATE_DMY">Fecha DD/MM/YYYY</option><option value="DATE_MDY">Fecha MM/DD/YYYY</option><option value="TIME_12">Hora 12 h</option><option value="TIME_24">Hora 24 h</option><option value="BOOLEAN">Sí/No</option><option value="LIST">Lista de valores</option><option value="IMAGE">Imagen</option><option value="PDF">PDF</option><option value="FILE">Archivo</option></select></div><div class="field"><label for="cfgOrder">Orden</label><input id="cfgOrder" type="number" min="0" step="1" value="10"></div></div><div class="buttons"><button id="cfgCancel" class="secondary" type="button">Cancelar</button><button class="primary" type="submit">Guardar</button></div></form></div>`;

const el=id=>document.getElementById(id);
const group=el('cfgGroup'),fieldsBox=el('cfgFields'),valuesBox=el('cfgValues'),statusBox=el('cfgStatus'),modal=el('cfgModal');
let token='',rows=[],roots={},selectedFieldId=null,selectedValueId=null;
const formatByType={TEXT:'TEXT',LONG_TEXT:'TEXT',EMAIL:'EMAIL',INTEGER:'INTEGER',DECIMAL:'DECIMAL',DATE_DMY:'DD/MM/YYYY',DATE_MDY:'MM/DD/YYYY',TIME_12:'HH12:MI AM',TIME_24:'HH24:MI',BOOLEAN:'TRUE/FALSE',LIST:'LIST',IMAGE:'FILE_REFERENCE',PDF:'FILE_REFERENCE',FILE:'FILE_REFERENCE'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function msg(text,type=''){statusBox.textContent=text||'';statusBox.className='config-status'+(type?' '+type:'')}
function currentRoot(){return roots[group.value]}
function fieldRows(){const root=currentRoot();return root?rows.filter(r=>String(r.id_parent)===String(root.id_sequence)&&r.deleted_at==null&&r.is_active!==false).sort((a,b)=>(a.display_order??9999)-(b.display_order??9999)||String(a.name).localeCompare(String(b.name),'es')):[]}
function selectedField(){return rows.find(r=>String(r.id_sequence)===String(selectedFieldId))||null}
function valueRows(){const f=selectedField();return f?rows.filter(r=>String(r.id_parent)===String(f.id_sequence)&&r.deleted_at==null&&r.is_active!==false).sort((a,b)=>(a.display_order??9999)-(b.display_order??9999)||String(a.name).localeCompare(String(b.name),'es')):[]}
function renderFields(){const fs=fieldRows();if(!fs.some(x=>String(x.id_sequence)===String(selectedFieldId)))selectedFieldId=null;fieldsBox.innerHTML=fs.length?fs.map(f=>`<div class="config-row ${String(f.id_sequence)===String(selectedFieldId)?'selected':''}" data-id="${f.id_sequence}"><div class="config-row-title">${esc(f.name)}</div><div class="config-row-meta">${esc(f.data_type)} · ${esc(f.format||'')}</div></div>`).join(''):'<div class="config-empty">No hay campos configurados.</div>';fieldsBox.querySelectorAll('.config-row').forEach(r=>r.onclick=()=>{selectedFieldId=r.dataset.id;selectedValueId=null;renderFields();renderValues()});renderValues()}
function renderValues(){const f=selectedField();el('cfgValuesTitle').textContent=f?`Valores hijos · ${f.name}`:'Valores hijos';el('cfgNewValue').disabled=!f||f.data_type!=='LIST';el('cfgEditValue').disabled=!selectedValueId;if(!f){valuesBox.innerHTML='<div class="config-empty">Selecciona un campo.</div>';return}if(f.data_type!=='LIST'){valuesBox.innerHTML=`<div class="config-empty">${esc(f.name)} no usa valores hijos.</div>`;return}const vs=valueRows();if(!vs.some(x=>String(x.id_sequence)===String(selectedValueId)))selectedValueId=null;valuesBox.innerHTML=vs.length?vs.map(v=>`<div class="config-row ${String(v.id_sequence)===String(selectedValueId)?'selected':''}" data-id="${v.id_sequence}"><div class="config-row-title">${esc(v.name)}</div><div class="config-row-meta">Orden ${v.display_order??'—'}</div></div>`).join(''):'<div class="config-empty">Esta lista todavía no tiene valores.</div>';valuesBox.querySelectorAll('.config-row').forEach(r=>r.onclick=()=>{selectedValueId=r.dataset.id;renderValues()})}
function openForm(mode,row=null){const isValue=mode==='value';el('cfgMode').value=mode;el('cfgId').value=row?.id_sequence||'';el('cfgParent').value=isValue?selectedFieldId:(currentRoot()?.id_sequence||'');el('cfgFormTitle').textContent=row?(isValue?'Modificar valor':'Modificar campo'):(isValue?'Nuevo valor':'Nuevo campo');el('cfgName').value=row?.name||'';el('cfgDescription').value=row?.description||'';el('cfgOrder').value=row?.display_order??10;el('cfgType').value=isValue?'TEXT':(row?.data_type||'TEXT');el('cfgType').disabled=isValue;modal.classList.add('open');modal.setAttribute('aria-hidden','false');setTimeout(()=>el('cfgName').focus(),20)}
function closeForm(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');el('cfgForm').reset();el('cfgType').disabled=false}
async function api(path,options={}){const r=await fetch(DATA_API_URL+path,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw new Error(await r.text());if(r.status===204)return null;const text=await r.text();return text?JSON.parse(text):null}
async function load(){try{const data=await api('/igldata?select=id_sequence,id_parent,name,description,data_type,format,display_order,is_active,deleted_at&deleted_at=is.null&order=display_order.asc,id_sequence.asc');rows=Array.isArray(data)?data:[];roots={};rows.filter(r=>r.id_parent==null).forEach(r=>roots[r.name]=r);renderFields();msg('')}catch(e){console.error(e);msg('No se pudo cargar la configuración.','error')}}
function payloadFromForm(){const mode=el('cfgMode').value,isValue=mode==='value',type=isValue?'TEXT':el('cfgType').value;return{id_parent:Number(el('cfgParent').value),name:el('cfgName').value.trim(),description:el('cfgDescription').value.trim()||el('cfgName').value.trim(),data_type:type,format:formatByType[type]||'TEXT',display_order:Number(el('cfgOrder').value||0),is_active:true,updated_at:new Date().toISOString()}}
el('cfgForm').addEventListener('submit',async e=>{e.preventDefault();const id=el('cfgId').value,payload=payloadFromForm();if(!payload.name)return;try{if(id){await api(`/igldata?id_sequence=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)})}else{delete payload.updated_at;await api('/igldata',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)})}closeForm();await load();msg('Guardado.','success');setTimeout(()=>msg(''),1200)}catch(err){console.error(err);msg('No se pudo guardar. Revisa que el nombre no esté repetido.','error')}});
el('cfgCancel').onclick=closeForm;modal.addEventListener('click',e=>{if(e.target===modal)closeForm()});group.onchange=()=>{selectedFieldId=null;selectedValueId=null;renderFields()};el('cfgNewField').onclick=()=>openForm('field');el('cfgEditField').onclick=()=>{const f=selectedField();if(f)openForm('field',f)};el('cfgNewValue').onclick=()=>{if(selectedField()?.data_type==='LIST')openForm('value')};el('cfgEditValue').onclick=()=>{const v=rows.find(r=>String(r.id_sequence)===String(selectedValueId));if(v)openForm('value',v)};

(async()=>{try{const [{initializeApp,getApps,getApp},{getAuth}]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js')]);const app=getApps().length?getApp():initializeApp(FIREBASE_CONFIG),auth=getAuth(app);if(typeof auth.authStateReady==='function')await auth.authStateReady();if(!auth.currentUser){msg('No hay una sesión activa.','error');return}token=await auth.currentUser.getIdToken();await load()}catch(e){console.error(e);msg('No se pudo iniciar Configuración.','error')}})();