-- America Es Tuya
-- Initial dynamic-data dictionary table
-- PostgreSQL

CREATE TABLE IF NOT EXISTS IGLDATA (
    ID_SEQUENCE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PARENT BIGINT NULL,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100) NULL,
    DATA_TYPE VARCHAR(5) NOT NULL,
    DISPLAY_ORDER INTEGER NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ NULL,
    DELETED_AT TIMESTAMPTZ NULL,

    CONSTRAINT FK_IGLDATA_PARENT
        FOREIGN KEY (ID_PARENT)
        REFERENCES IGLDATA (ID_SEQUENCE)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT CK_IGLDATA_NOT_SELF_PARENT
        CHECK (ID_PARENT IS NULL OR ID_PARENT <> ID_SEQUENCE),

    CONSTRAINT CK_IGLDATA_DATA_TYPE
        CHECK (DATA_TYPE IN ('T', 'TL', 'I', 'N', 'D', 'DT', 'B', 'LV', 'V', 'IMG', 'PDF', 'FILE')),

    CONSTRAINT CK_IGLDATA_DISPLAY_ORDER
        CHECK (DISPLAY_ORDER IS NULL OR DISPLAY_ORDER >= 0),

    CONSTRAINT CK_IGLDATA_DELETE_STATE
        CHECK (DELETED_AT IS NULL OR IS_ACTIVE = FALSE)
);

-- A root field name must be unique among root definitions.
CREATE UNIQUE INDEX IF NOT EXISTS UX_IGLDATA_ROOT_NAME
    ON IGLDATA (UPPER(NAME))
    WHERE ID_PARENT IS NULL AND DELETED_AT IS NULL;

-- A value/child name must be unique inside its parent list.
CREATE UNIQUE INDEX IF NOT EXISTS UX_IGLDATA_PARENT_NAME
    ON IGLDATA (ID_PARENT, UPPER(NAME))
    WHERE ID_PARENT IS NOT NULL AND DELETED_AT IS NULL;

CREATE INDEX IF NOT EXISTS IX_IGLDATA_PARENT
    ON IGLDATA (ID_PARENT);

CREATE INDEX IF NOT EXISTS IX_IGLDATA_ACTIVE
    ON IGLDATA (IS_ACTIVE)
    WHERE DELETED_AT IS NULL;

-- Automatically maintain UPDATED_AT whenever a row is modified.
CREATE OR REPLACE FUNCTION FN_IGLDATA_SET_UPDATED_AT()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS TRG_IGLDATA_SET_UPDATED_AT ON IGLDATA;

CREATE TRIGGER TRG_IGLDATA_SET_UPDATED_AT
BEFORE UPDATE ON IGLDATA
FOR EACH ROW
EXECUTE FUNCTION FN_IGLDATA_SET_UPDATED_AT();

-- Initial examples are intentionally not inserted here.
-- We will load production catalogue values separately after defining
-- the final business vocabulary for DATA_TYPE and list values.
